import { nowTimestamp } from "../utils/dateUtils.js";
import { createUuid } from "../utils/idUtils.js";

const SEQUENCES = {
  principal: { label: "مدير المدرسة", criteria: [["relationships", "علاقات المعلم الإنسانية مع زملائه وإدارة المدرسة", 2], ["cooperation", "التعاون مع إدارة المدرسة والكادر الإداري وتنفيذ التوجيهات", 3], ["meetings", "حضور الاجتماعات والدورات", 2], ["complaints", "شكاوى أولياء الأمور أو المتعلمين", 3]] },
  deputy: { label: "وكيل المدرسة", criteria: [["delivery", "تسليم ما يطلب منه في الوقت المحدد", 2], ["grade_record", "تفعيل سجل رصد الدرجات أسبوعيًا", 2], ["attendance", "عدم الخروج من المدرسة أثناء الدوام المدرسي", 2], ["correction", "تصحيح الكتب والدفاتر والمتابعة الشهرية", 2], ["accuracy", "رصد الدرجات بدقة", 2], ["supervision", "الإشراف الفعال على الطابور والراحة والانصراف", 3]] },
  educational_supervisor: { label: "المشرف التربوي", criteria: [["supervisor_form", "استمارة المشرف التربوي", 20], ["special_form", "استمارة التوجيه التخصصي الداخلي", 10], ["tests", "القدرة على وضع اختبارات تحريرية متميزة", 2], ["planning", "الالتزام بالتحضير اليومي وتسليمه للمختص", 2], ["screen", "تفعيل الشاشة المتحركة أو الثابتة", 2], ["appendices", "تفعيل ملاحق دفتر التحضير", 2]] },
  administrative_supervisor: { label: "المشرف الإداري", criteria: [["morning", "المشاركة الفاعلة في طابور الصباح", 2], ["lesson_time", "ضبط زمن الحصة ابتداءً وانتهاءً", 2], ["class_exit", "عدم الخروج من الصف أثناء الحصة", 2], ["discipline", "حل مشكلات المتعلمين بأساليب تربوية", 2], ["parent_contact", "التواصل مع ولي الأمر وتفعيل سجل التواصل", 4], ["building", "الاهتمام بالمبنى والأثاث والمظهر العام", 2], ["notebooks", "متابعة وتصويب دفاتر المتعلمين أسبوعيًا", 4], ["dismissal", "تنظيم خروج المتعلمين أثناء الراحة ونهاية الدوام", 3], ["values", "متابعة الواجبات والقدوة الحسنة والقيم", 2]] },
  secretary_computer: { label: "سكرتير المدرسة / وحدة الحاسوب", criteria: [["work_time", "الالتزام بالدوام الدراسي", 2], ["cover", "تفعيل حصص التغطية والحصص الإضافية", 2], ["matching", "تطابق التقييم مع سجل الدرجات", 2], ["android", "تفعيل تطبيق الأندرويد", 2]] },
  activity_supervisor: { label: "مشرف الأنشطة", criteria: [["broadcast", "إعداد الإذاعة المدرسية والإشراف عليها", 2], ["activities", "المشاركة الجادة في الأنشطة المدرسية المختلفة", 4]] },
  social_specialist: { label: "الاختصاصي الاجتماعي", criteria: [["pioneer", "تفعيل دور المعلم كرائد فصل وتعاون الكادر", 2], ["values", "غرس القيم والمفاهيم التربوية ومتابعتها", 2]] },
};

function esc(value, safe) { return safe(String(value ?? "")); }
function totalOf(sequenceKey, scores) { return (SEQUENCES[sequenceKey]?.criteria || []).reduce((sum, [, , max]) => sum + Math.min(max, Math.max(0, Number(scores?.[arguments[1]] || 0))), 0); }

export function createStaffEvaluationsModule(getContext) {
  const definition = (key) => SEQUENCES[key] || SEQUENCES.principal;
  function normalizeEvaluation(item = {}) {
    const get = (a, b) => item[a] ?? item[b];
    return { id: get("id", "id") || createUuid(), schoolId: get("schoolId", "school_id") || "", teacherId: get("teacherId", "teacher_id") || "", teacherName: get("teacherName", "teacher_name") || "", subjectName: get("subjectName", "subject_name") || "", sequenceKey: get("sequenceKey", "sequence_key") || "principal", evaluatedAt: get("evaluatedAt", "evaluated_at") || new Date().toISOString().slice(0, 10), scores: get("scores", "scores") || {}, total: Number(get("total", "total") || 0), maxTotal: Number(get("maxTotal", "max_total") || 0), notes: get("notes", "notes") || "", evaluatedBy: get("evaluatedBy", "evaluated_by") || "", createdAt: get("createdAt", "created_at") || "", updatedAt: get("updatedAt", "updated_at") || "" };
  }
  function openEvaluation(id = "") { const { state, render } = getContext(); state.modal = { type: "staff_evaluation", id }; render(); }
  function renderPage() {
    const { state, safe, icons, canManageStaffEvaluations } = getContext();
    const filters = state.staffEvaluationFilters || {};
    const rows = (state.staffEvaluations || []).filter((x) => filters.roleKey === "all" || x.sequenceKey === filters.roleKey).filter((x) => !filters.search || `${x.teacherName} ${x.subjectName}`.includes(filters.search)).sort((a, b) => Number(b.total) - Number(a.total));
    return `<main class="staff-evaluation-page page-shell"><div class="page-heading"><div><span class="eyebrow">تقييم الأداء</span><h1>تقييم الموظفين والمعلمين</h1><p>استمارات مبنية على بنود التقييم الإداري التفصيلي.</p></div>${canManageStaffEvaluations() ? `<button class="button primary" onclick="actions.openStaffEvaluation('')">${icons.plus || "+"} إضافة تقييم</button>` : ""}</div>
      <section class="evaluation-tools"><input class="input" placeholder="ابحث باسم المعلم أو المادة" value="${esc(filters.search, safe)}" oninput="actions.setStaffEvaluationFilter('search', this.value)"><select class="input" onchange="actions.setStaffEvaluationFilter('roleKey', this.value)"><option value="all">كل التسلسلات</option>${Object.entries(SEQUENCES).map(([key, value]) => `<option value="${key}" ${filters.roleKey === key ? "selected" : ""}>${safe(value.label)}</option>`).join("")}</select><button class="button ghost" onclick="actions.exportTeacherTemplate()">تصدير نموذج المعلمين</button><label class="button ghost file-button">استيراد المعلمين<input type="file" accept=".csv,.xlsx,.xls" hidden onchange="actions.importTeacherDirectory(this.files[0])"></label></section>
      <section class="evaluation-report-actions"><strong>التقارير</strong><button class="button ghost" onclick="actions.printStaffEvaluationReport('ranked')">ترتيب الأعلى</button><button class="button ghost" onclick="actions.printStaffEvaluationReport('summary')">ملخص النتائج</button><button class="button ghost" onclick="actions.printStaffEvaluationReport('full')">التقرير العام</button></section>
      <section class="evaluation-list">${rows.length ? rows.map((item) => `<article class="evaluation-card"><div><strong>${safe(item.teacherName)}</strong><span>${safe(item.subjectName)} · ${safe(definition(item.sequenceKey).label)}</span></div><b>${safe(item.total)} / ${safe(item.maxTotal)}</b><button class="icon-btn" onclick="actions.openStaffEvaluation('${item.id}')">${icons.edit || "✎"}</button></article>`).join("") : `<div class="empty">لا توجد تقييمات بعد. أضف أول تقييم من الزر أعلاه.</div>`}</section></main>`;
  }
  function renderModal(id = "") {
    const { state, safe, icons } = getContext(); const old = state.staffEvaluations.find((x) => x.id === id) || normalizeEvaluation({}); const sequence = definition(old.sequenceKey); const teachers = state.teacherDirectory || [];
    return `<div class="modal-backdrop"><section class="modal-card staff-evaluation-modal"><header><h2>${id ? "تعديل تقييم" : "إضافة تقييم موظف"}</h2><button class="icon-btn" onclick="actions.closeModal()">×</button></header><form onsubmit="actions.saveStaffEvaluation(event); return false;"><input type="hidden" name="id" value="${esc(old.id, safe)}"><div class="evaluation-form-grid"><label class="field"><span>التسلسل الوظيفي</span><select name="sequenceKey" onchange="this.form.submitSequence?.()" required>${Object.entries(SEQUENCES).map(([key, value]) => `<option value="${key}" ${old.sequenceKey === key ? "selected" : ""}>${safe(value.label)}</option>`).join("")}</select></label><label class="field"><span>المعلم</span><select name="teacherId" required><option value="">اختر اسم المعلم</option>${teachers.map((t) => `<option value="${t.id}" data-subject="${esc(t.subjectName, safe)}" ${old.teacherId === t.id ? "selected" : ""}>${safe(t.teacherName)} — ${safe(t.subjectName)}</option>`).join("")}</select></label><label class="field"><span>المادة</span><input name="subjectName" value="${esc(old.subjectName, safe)}" placeholder="تظهر من سجل المعلمين أو اكتبها" required></label><label class="field"><span>تاريخ التقييم</span><input type="date" name="evaluatedAt" value="${esc(old.evaluatedAt, safe)}" required></label></div><div class="evaluation-criteria-grid">${sequence.criteria.map(([key, label, max]) => `<label class="evaluation-criterion-card"><span>${safe(label)}</span><small>الحد الأعلى ${safe(max)}</small><input class="evaluation-score-input" type="number" name="score_${key}" min="0" max="${max}" step="0.5" value="${esc(old.scores?.[key] ?? "", safe)}" placeholder="0 - ${max}" required><button type="button" class="mini-button" onclick="this.previousElementSibling.value='${max}'">الحد الأعلى</button></label>`).join("")}</div><label class="field"><span>ملاحظات</span><textarea name="notes" rows="3" placeholder="اكتب ملاحظة اختيارية">${esc(old.notes, safe)}</textarea></label><footer><button class="button primary" type="submit">حفظ التقييم</button>${id ? `<button class="button danger" type="button" onclick="actions.deleteStaffEvaluation('${id}')">حذف</button>` : ""}</footer></form></section></div>`;
  }
  async function saveEvaluation(event) {
    const { state, cloud, supabase, render, showToast, scopedSchoolId } = getContext(); const form = new FormData(event.currentTarget); const id = String(form.get("id") || createUuid()); const sequenceKey = String(form.get("sequenceKey") || "principal"); const sequence = definition(sequenceKey); const scores = {}; let total = 0; for (const [key, , max] of sequence.criteria) { const value = Number(form.get(`score_${key}`)); if (!Number.isFinite(value) || value < 0 || value > max) { showToast(`تحقق من درجة: ${key}`); return; } scores[key] = value; total += value; }
    const existing = state.staffEvaluations.find((x) => x.id === id); const data = { schoolId: scopedSchoolId(), teacherId: String(form.get("teacherId") || ""), teacherName: state.teacherDirectory.find((x) => x.id === String(form.get("teacherId")))?.teacherName || "", subjectName: String(form.get("subjectName") || ""), sequenceKey, evaluatedAt: String(form.get("evaluatedAt") || new Date().toISOString().slice(0, 10)), scores, total, maxTotal: sequence.criteria.reduce((s, [, , max]) => s + max, 0), notes: String(form.get("notes") || ""), evaluatedBy: state.currentUser?.id || "", updatedAt: nowTimestamp(), createdAt: existing?.createdAt || nowTimestamp() };
    if (!data.teacherName) { showToast("اختر اسم المعلم"); return; } state.staffEvaluations = [...state.staffEvaluations.filter((x) => x.id !== id), normalizeEvaluation({ id, ...data })]; state.modal = null; render(); try { await supabase.saveCloudDoc("staffEvaluations", id, data, Boolean(existing)); showToast("تم حفظ التقييم"); } catch (error) { console.error(error); showToast("حفظ محليًا، تعذر الإرسال إلى قاعدة البيانات"); }
  }
  async function deleteEvaluation(id) { const { state, cloud, supabase, render, showToast } = getContext(); state.staffEvaluations = state.staffEvaluations.filter((x) => x.id !== id); state.modal = null; render(); try { await supabase.deleteCloudDoc("staffEvaluations", id); } catch (error) { console.error(error); } showToast("تم حذف التقييم"); }
  function setFilter(key, value) { const { state, render } = getContext(); state.staffEvaluationFilters = { ...state.staffEvaluationFilters, [key]: value }; render(); }
  function importTeachers(file) { if (!file) return; const { state, render, showToast } = getContext(); const reader = new FileReader(); reader.onload = async () => { const lines = String(reader.result || "").replace(/^\uFEFF/, "").split(/\r?\n/).map((line) => line.trim()).filter(Boolean); const start = /اسم المعلم|teacher/i.test(lines[0] || "") ? 1 : 0; const items = lines.slice(start).map((line) => { const [teacherName, subjectName] = line.split(/[,\t;]/).map((x) => String(x || "").trim()); return teacherName && subjectName ? normalizeEvaluation({ id: createUuid(), teacherName, subjectName, active: true }) : null; }).filter(Boolean).map((x) => ({ id: x.id, teacherName: x.teacherName, subjectName: x.subjectName, active: true, schoolId: getContext().scopedSchoolId(), createdBy: state.currentUser?.id || "" })); state.teacherDirectory = [...state.teacherDirectory, ...items]; for (const item of items) { try { await getContext().supabase.saveCloudDoc("teacherDirectory", item.id, item, false); } catch (error) { console.error(error); } } render(); showToast(`تم استيراد ${items.length} معلماً`); }; reader.readAsText(file, "utf-8"); }
  function exportTeacherTemplate() { getContext().downloadBlob("قائمة_المعلمين.csv", "\uFEFFاسم المعلم,اسم المادة\n", "text/csv;charset=utf-8"); }
  function printReport(mode = "ranked") { const { state } = getContext(); const rows = [...state.staffEvaluations].sort((a, b) => Number(b.total) - Number(a.total)); const body = mode === "summary" ? rows.map((x) => `<tr><td>${x.teacherName}</td><td>${x.subjectName}</td><td>${x.total}/${x.maxTotal}</td></tr>`).join("") : rows.map((x) => `<tr><td>${x.teacherName}</td><td>${x.subjectName}</td><td>${definition(x.sequenceKey).label}</td><td>${x.total}/${x.maxTotal}</td><td>${mode === "full" ? Object.entries(x.scores || {}).map(([key, value]) => `${key}: ${value}`).join(" | ") : ""}</td></tr>`).join(""); const win = window.open("", "_blank"); if (!win) return; win.document.write(`<html dir="rtl"><head><meta charset="utf-8"><title>تقرير تقييم الموظفين</title><style>body{font-family:Arial;padding:24px}table{width:100%;border-collapse:collapse}th,td{border:1px solid #999;padding:8px;text-align:right}</style></head><body><h1>تقرير تقييم الموظفين</h1><table><thead><tr><th>المعلم</th><th>المادة</th>${mode === "summary" ? "" : "<th>التسلسل</th>"}<th>النتيجة</th>${mode === "full" ? "<th>البنود</th>" : ""}</tr></thead><tbody>${body}</tbody></table><script>window.print()</script></body></html>`); win.document.close(); }
  return { normalizeEvaluation, renderPage, renderModal, openEvaluation, saveEvaluation, deleteEvaluation, setFilter, printReport, importTeachers, exportTeacherTemplate, sequenceOptions: Object.entries(SEQUENCES).map(([key, value]) => ({ key, label: value.label })), getSequenceDefinition: definition };
}
